version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "guibais"
    assignees:
      - "guibais"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "guibais"
    assignees:
      - "guibais"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "guibais"
    assignees:
      - "guibais"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
